
# Overview page
## Top Used Dexs
QUERY_TOP_DEXS = """
SELECT
  APP_ID,
	COUNT(APP_ID) AS TRADING_FREQUENCY
  FROM TXNS_ON_DEXS
  WHERE TX_DATE BETWEEN '{start_date}' AND '{end_date}'
	GROUP BY APP_ID
ORDER BY TRADING_FREQUENCY DESC LIMIT 10
"""

## Top Traded Tokens
QUERY_TOP_TOKENS = """
SELECT
  ASSET_ID, TOKEN_NAME,
	COUNT(ASSET_ID) AS TRADING_FREQUENCY
  FROM TXNS_OF_HOT_TOKENS
  WHERE TX_DATE BETWEEN '{start_date}' AND '{end_date}'
	GROUP BY ASSET_ID, TOKEN_NAME
ORDER BY TRADING_FREQUENCY DESC LIMIT 10
"""

# Hot DEXs page
## Compare Dexs Usage
QUERY_DEX_USAGE = """
SELECT APP_ID,
	TX_DATE,
	COUNT(APP_ID) AS TRADING_FREQUENCY
  FROM TXNS_ON_DEXS
  WHERE
    TX_DATE BETWEEN '{start_date}' AND '{end_date}'
  	AND APP_ID IN (SELECT APP_ID FROM DEXS)
	GROUP BY APP_ID, TX_DATE
ORDER BY TX_DATE ASC
"""

## Hot DEX Platforms by Trading Volume
QUERY_DEX_TRADING_VOLUME = """

"""

# Hot Tokens page

## Compare Token(s) Usage during a Time Period
QUERY_TOKEN_USAGE = """
SELECT
	ASSET_ID,
	TX_DATE,
	COUNT(ASSET_ID) AS TRADING_FREQUENCY
  FROM TXNS_OF_HOT_TOKENS
  WHERE
    TX_DATE BETWEEN '{start_date}' AND '{end_date}'
  	AND ASSET_ID IN (SELECT ASSET_ID FROM HOT_TOKENS)
	GROUP BY ASSET_ID, TX_DATE
ORDER BY TX_DATE ASC
"""

## Hot Tokens by Trading Volume during a Time Period