
CREATE VIEW TXNS_OF_HOT_TOKENS AS

SELECT DISTINCT
  AXFER_TXNS.ASSET_ID,
	HOT_TOKENS.TOKEN_NAME,
	AXFER_TXNS.AMOUNT,
	HOT_TOKENS.DECIMALS,
	DATE(AXFER_TXNS.ROUND_TIME) AS TX_DATE,
	AXFER_TXNS.RELATED_TX
FROM AXFER_TXNS
JOIN HOT_TOKENS ON AXFER_TXNS.ASSET_ID = HOT_TOKENS.ASSET_ID;



CREATE VIEW TXNS_ON_DEXS AS
SELECT DISTINCT
  APP_TXNS.APP_ID,
	DEXS_DISTINCT.PLATFORM,
	DATE(APP_TXNS.ROUND_TIME) AS TX_DATE,
	APP_TXNS.RELATED_TX
FROM APP_TXNS
JOIN
	(SELECT DISTINCT DEXS.APP_ID,
			DEXS.PLATFORM
		FROM DEXS) DEXS_DISTINCT ON APP_TXNS.APP_ID = DEXS_DISTINCT.APP_ID;